### ISSUE TITLE
Team mentions don't work

### ISSUE THREAD

**Issue by balloob** [home-assistant/codeowners-mention#1]
Because GitHub Actions is not part of our org, it won't tag teams when mentioned.

**Comment by robbiet480** [comment]
Fixed by migrating the bot from GitHub Actions to Heroku.

**Comment by robbiet480** [comment]
Nope, thought it was, but not yet. Putting a @homeassistant token in.

**Comment by robbiet480** [comment]
Okay, actually fixed. Had to add read only organization members permission to the app as per https://github.com/probot/probot/issues/337. Did not put a @homeassistant token in.
