### ISSUE TITLE
Feature Request: respond to breaking-change label

### ISSUE THREAD

**Issue by balloob** [home-assistant/codeowners-mention#2]
When the breaking change label is applied, we should respond with a comment that contains a template and the implications of the breaking change. Comment should preferably be based off a markdown file in this repo. 

>  Your PR has been marked as a breaking change. Please describe what has changed and what users need to do. [Examples of breaking changes.](https://www.home-assistant.io/blog/2019/04/03/release-91/#breaking-changes)

**Comment by robbiet480** [comment]
This feels like more of a issue for LabelBot. Dunno how I feel about scope creep outside of CODEOWNERS mentioning.

**Comment by balloob** [comment]
Fine with that too.
